function [tau_rw,h_w] = reactionWheelActuator(tau_cmd,h_w,params,dt)

% This function calculates the actual torque generated by actuation limits
% and updates angular momentum readings.

% Torque Saturation
tau_rw = max(min(tau_cmd, params.tau_max), -params.tau_max);

% Momentum integration (reaction torque)
h_w = h_w - tau_rw * dt;

% Momentum saturation
for i = 1:3
    if abs(h_w(i)) >= params.h_max
        tau_rw(i) = 0;
    end
end


end
